# Generated by Django 5.2.1 on 2026-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(default=list),
        ),
    ]
